# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/yamamotoshu1127
    environment:
      - GO111MODULE: "on"
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
