# Golang CircleCI 2.0 configuration file
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/repo
    environment:
      - GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Install golint
          command: go get golang.org/x/lint/golint
      - run:
          name: Run Build
          command: find modules/ -name Makefile | while read file; do pushd `dirname $file`; make build; make clean; popd; done
      - run:
          name: Run lint
          command: golint --set_exit_status modules/...
      - run:
          name: Run tests
          command: find modules/* -type d | while read dir; do pushd $dir; if ls *_test.go > /dev/null 2>&1; then go test ./...; fi; popd; done
