version: 2.1
executors:
  default:
    working_directory: ~/{{REPO_NAME}}
    docker:
      - image: circleci/golang:1.12
    environment:
      - GO111MODULE: "on"
jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go get -v -t -d ./...
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Run Build
          command: find modules/ -name Makefile | while read file; do pushd `dirname $file`; make build; popd; done
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install golint
          command: go get golang.org/x/lint/golint
      - run:
          name: Run lint
          command: find modules/ -name Makefile | while read file; do pushd `dirname $file`; make lint; popd; done
  test:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Run tests
          command: find modules/ -name Makefile | while read file; do pushd `dirname $file`; make test; popd; done

workflows:
  version: 2
  build_lint_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup

