# Golang CircleCI 2.0 configuration file
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/{{REPO_NAME}}
    environment:
      - GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go get -v -t -d ./...
      - run:
          name: Install golint
          command: go get golang.org/x/lint/golint
      - run:
          name: Run Build
          command: find modules/ -name Makefile | while read file; do pushd `dirname $file`; make build; popd; done
      - run:
          name: Run lint
          command: find modules/ -name Makefile | while read file; do pushd `dirname $file`; make lint; popd; done
      - run:
          name: Run tests
          command: find modules/ -name Makefile | while read file; do pushd `dirname $file`; make test; popd; done
