version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      - GO111MODULE: "on"
    working_directory: ~/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get golang.org/x/lint/golint
      - run: find modules/ -name Makefile | while read file; do pushd `dirname $file`; make build; make test; make lint; popd; done
      - run: echo "Hello Hoge CircleCI World!"
